# Application Settings
app:
  input_dir: "data/raw"
  output_dir: "data/processed"
  temp_dir: "data/temp"
  default_input_file: "Sample Clean aCRF (dragged).pdf"
  temp_markdown_name: "temp_markdown.json"

# Ollama Settings
ollama:
  model: "llama3.1:70b"
  options:
    temperature: 0.0
    top_p: 0.9
    top_k: 40
    num_ctx: 4096
    num_predict: 2560
    repeat_penalty: 1.1
    presence_penalty: 0.0
    frequency_penalty: 0.0
    mirostat: 0
    mirostat_tau: 5.0
    mirostat_eta: 0.1
    seed: 42

# Logging Settings
logging:
  level: INFO
  file_path: "logs/app.log"